name: CD

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install dependencies
        run: npm ci
      - name: Build backend
        run: npm run build -w backend

      - name: Login to gcloud registry
        uses: elgohr/gcloud-login-action@v2
        with:
          account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Create Docker Image Backend
        uses: aevea/action-kaniko@v0.10.0
        with:
          image: '${{ secrets.DOCKER_IMAGE }}'
          path: packages/backend
          cache: true
          cache_registry: '${{ secrets.DOCKER_REGISTRY }}'
